import React from 'react'
import { Heading, SubTitle } from '@/components/elements'
import { Container, Section } from '@/components/layouts'
import {
    Accordion,
    AccordionContent,
    AccordionItem,
    AccordionTrigger,
} from '@/components/elements/accordian'

const faqs = [
    {
        question: "How does solar energy work?",
        answer: "Solar panels convert sunlight into electricity using photovoltaic (PV) cells. The electricity generated can power your home or business, reducing your reliance on the grid and lowering your electricity bills."
    },
    {
        question: "What are the benefits of installing solar panels?",
        answer: "Solar panels can significantly reduce or even eliminate your electricity bills, provide protection against rising energy costs, increase your property value, and reduce your carbon footprint. Additionally, you may qualify for government incentives or subsidies."
    },
    {
        question: "How much can I save by switching to solar?",
        answer: "Savings depend on your energy usage, the size of the solar system, and your local electricity rates. On average, customers save 50-100% on their electricity bills. We provide a customized savings estimate during the consultation process."
    },
    {
        question: "Are there any government incentives or subsidies available for solar installations?",
        answer: "Yes, many government programs offer financial incentives, such as rebates, tax credits, and subsidies. We help you navigate these programs to maximize your benefits, including potential savings of up to ₹78,000 or more."
    },
    {
        question: "How long does the installation process take?",
        answer: "The entire process, from initial consultation to installation, typically takes 2 to 4 weeks, depending on the size of the system and local permitting requirements. Our team will handle all the details to ensure a smooth installation."
    },
    {
        question: "What maintenance is required for solar panels?",
        answer: "Solar panels require very little maintenance. They are designed to be durable and withstand various weather conditions. We recommend occasional cleaning and a professional check-up every few years to ensure optimal performance."
    },
    {
        question: "What happens if my solar panels produce more electricity than I use?",
        answer: "Any excess electricity generated by your solar panels can be fed back into the grid. Depending on your location, you may receive credits on your utility bill or even get paid for the extra energy produced."
    },
    {
        question: "How long do solar panels last?",
        answer: "Most solar panels come with a warranty of 25 years or more and can last 30 years or longer with proper maintenance. They continue to generate electricity well beyond their warranty period, though their efficiency may decrease slightly over time."
    },
    {
        question: "Will solar panels work during cloudy or rainy days?",
        answer: "Yes, solar panels can still generate electricity on cloudy or rainy days, though their efficiency may be reduced. However, they work best in direct sunlight and will produce more power during sunny conditions."
    },
    {
        question: "Is my roof suitable for solar panels?",
        answer: "Most roofs are suitable for solar panels, but factors like roof orientation, angle, and shading from nearby trees or buildings can affect efficiency. We conduct a thorough assessment to determine the best solar solution for your property."
    },
    {
        question: "What if I need to move after installing solar panels?",
        answer: "Solar panels can increase the value of your home, making it more attractive to potential buyers. In most cases, you can sell the property with the solar system included, or you may be able to transfer the panels to your new home."
    },
    {
        question: "How do I get started with a solar installation?",
        answer: "Simply contact us to schedule a free consultation. Our team will assess your energy needs, evaluate your property, and provide a customized proposal outlining your potential savings and installation options."
    }
]

const b2bFaqs = [
    {
        'question': 'What does Lead2Solar do for solar installers?',
        'answer': 'Lead2Solar connects solar installers with high-quality, location-specific leads through our digital platform. We focus on growing your business by providing verified leads, boosting your online presence, and offering tailored marketing solutions to help increase sales.'
    },
    {
        'question': 'How does the lead verification process work?',
        'answer': 'Our team double-verifies every lead before it reaches you. This process ensures that all leads are genuine and meet quality standards, so you can confidently pursue them without unnecessary follow-up.'
    },
    {
        'question': 'Can I select leads from specific locations only?',
        'answer': 'Yes, with Lead2Solar, you can customize your lead preferences to receive leads from your chosen locations. This ensures that you`re only connecting with customers in the areas that best suit your business needs.'
    },
    {
        'question': 'Is there flexibility in the subscription plans?',
        'answer': 'Absolutely! We offer a range of subscription plans that can be tailored to your business size, budget, and growth goals. You can also choose to join our WhatsApp group for additional networking and market insights.'
    },
    {
        'question': 'How will Lead2Solar help me grow my business?',
        'answer': 'By connecting you with pre-verified leads and offering customized digital marketing solutions, we help increase your sales and online visibility. This leads to sustainable growth, a stronger client base, and a thriving business in the solar industry.'
    }
]

interface FAQProps {
    isB2B?: boolean;
}

export default function FAQ({ isB2B = false }: FAQProps) {
    const faqList = isB2B ? b2bFaqs : faqs;
    return (
        <Section className="bg-secondary-950 rounded-3xl py-16">
            <Container>
                <SubTitle subTitle={'FAQs'} />
                <Heading as="h2" className="text-section leading-none text-white">
                    Frequently Asked Questions
                </Heading>
                <Accordion type="single" collapsible className="w-full mt-8">
                    {faqList.map((faq, index) => (
                        <AccordionItem key={index} value={`item-${index}`}>
                            <AccordionTrigger className='text-primary-50 text-left text-xl'>{index + 1}) {faq.question}</AccordionTrigger>
                            <AccordionContent className='text-md text-beige-primary opacity-70 text-md pl-2'>
                                <i>
                                    {faq.answer}
                                </i>
                            </AccordionContent>
                        </AccordionItem>
                    ))}
                </Accordion>
            </Container>
        </Section>
    )
}
